version: '3.6'
services:
  node:
    build: .
    ports:
      - "8332"
      - "7042"
    volumes:
      - /home/bitcoin
      - ./elements.conf:/elements.conf
    command: >
      elementsd
        -conf=/elements.conf

